create favorites section
VitaliyYakovenko/team-proj pull request #3
Opened 2022-10-30 19:09 UTC by Whitelili

2022-10-30 23:02 UTC, AlluringUnicorn requested changes

2022-10-30 23:02 UTC, AlluringUnicorn commented on src/partials/favorites.html
> +            sizes="(min-width:1280px) 33vw, (min-width:768) 50vw, 100vw"
На ширині 1280px  на dpr 1 і 2 грузяться картинки tab і mob замість desk

2022-10-31 08:38 UTC, Whitelili commented on src/sass/_favorites.scss
> +  background-color: $bg-main-color;
это не белый , это background: #F5F5F5;

2022-10-31 08:40 UTC, Whitelili commented on src/partials/favorites.html
> +<div class="container favorites">
в макете написано favOrites без U

2022-10-31 14:14 UTC, merged